## A basic GitHub Actions workflow for your Quarkus application.

name: Build

on:
  push:
    branches:
      - master
      - feature/*
      - bugfix/*
    tags:
      - '*'

jobs:
  build:
    name: "Build Image & push"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Determine Channel
        id: channel
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "channel=stable" >> $GITHUB_OUTPUT
          else
            echo "channel=staging" >> $GITHUB_OUTPUT
          fi
      - name: Determine Version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          fi
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image to GitHub Container Registry
        env:
          REGISTRY: ghcr.io
          GROUP: ${{ github.repository_owner }}
          IMAGE: ${{ github.event.repository.name }}
          K8S_NAMESPACE: ${{ github.event.repository.name }}
        run: |
          echo "Version $VERSION"
          ./gradlew build \
            -Pversion=$VERSION \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=$REGISTRY \
            -Dquarkus.container-image.group=$GROUP \
            -Dquarkus.container-image.name=$IMAGE \
            -Dquarkus.kubernetes.namespace=$K8S_NAMESPACE \
            -Dquarkus.operator-sdk.bundle.channels=${{ steps.channel.outputs.channel }}
      
        
