## A basic GitHub Actions workflow for your Quarkus application.

name: Update Catalog

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build catalog & push"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Get tags
        id: get_tags
        run: |
          git fetch --tags
          tags=$(git tag --list "1.*" --sort=v:refname | paste -sd "," -)
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Generate YAML file
        env:
          OPERATOR_PATH: "./catalog/minecraft-catalog/minecraft-operator/minecraft-operator-template.yaml"
        run: |
          echo "Schema: olm.semver" > $OPERATOR_PATH
          echo "GenerateMajorChannels: true" >> $OPERATOR_PATH
          echo "GenerateMinorChannels: true" >> $OPERATOR_PATH
          echo "Stable:" >> $OPERATOR_PATH
          echo "  Bundles:" >> $OPERATOR_PATH
          IFS=',' read -ra TAGS <<< "${{ steps.get_tags.outputs.tags }}"
          for tag in "${TAGS[@]}"
          do
            echo "  - Image: ghcr.io/merkeg/minecraft-operator-bundle:$tag" >> $OPERATOR_PATH
          done
      - name: Get Template contents
        run: cat ./catalog/minecraft-catalog/minecraft-operator/minecraft-operator-template.yaml
      - name: Build OPM catalog
        env:
          OPERATOR_TEMPLATE_PATH: "./catalog/minecraft-catalog/minecraft-operator/minecraft-operator-template.yaml"
          CATALOG_PATH: "./catalog/minecraft-operator/catalog.yaml"
        run: |
          ./catalog/opm alpha render-template semver -o yaml < $OPERATOR_TEMPLATE_PATH > CATALOG_PATH
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push catalog
        uses: docker/build-push-action@v3
        with:
          context: ./catalog
          file: ./catalog/minecraft-catalog.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-catalog:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
        
